esphome:
  name: watermeter
  platform: ESP8266
  board: d1_mini

external_components:
   #use from main branch in GitHub
 - source: "github://ajvdw/pulse2_meter"
   components: [pulse2_meter]
    
sensor: 
  - platform: pulse2_meter
    pin_a: D5
    pin_b: D6
    id: watermeter1
    unit_of_measurement: 'l/min'
    name: waterverbruik
    timeout: 2 min
    icon: mdi:water
    internal_filter: 200ms
    total:
      unit_of_measurement: 'm³'
      accuracy_decimals: 3
      name: 'watertotal'
      filters:
      - offset: 3216868
      - multiply: 0.001


# Enable logging
logger:

# Enable Home Assistant API
api:


ota:
  password: "????????????????"

wifi:
  ssid: "??????"
  password: "??????????"



  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waterlezer Fallback Hotspot"
    password: "??????????????"

captive_portal:
